require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityBluetoothLe', :path => '../../node_modules/@capacitor-community/bluetooth-le'
  pod 'CapacitorCommunityNordicDfu', :path => '../../node_modules/capacitor-community-nordic-dfu'
  pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem'
  pod 'CapawesomeCapacitorFilePicker', :path => '../../node_modules/@capawesome/capacitor-file-picker'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)

  # Get main project development team id
  dev_team = ""
  project = installer.aggregate_targets.first.user_project
  project.targets.each do |target|
      target.build_configurations.each do |config|
          if dev_team.empty? && !config.build_settings['DEVELOPMENT_TEAM'].nil?
              dev_team = config.build_settings['DEVELOPMENT_TEAM']
          end
      end
  end
  
  # Apply development team to all pod targets
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['DEVELOPMENT_TEAM'] = dev_team
          config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'
          config.build_settings['CODE_SIGN_IDENTITY'] = 'iPhone Developer'
          config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
      end
  end
end
